name: Parasoft Coverage
on:
  workflow_dispatch:
permissions:
    checks: write
    contents: write
    actions: read

jobs:
  build:
    name: Parasoft Coverage Action
    runs-on: self-hosted
    strategy:
      max-parallel: 1

    steps:
      - name: Cleanup temp directories
        run: |
          if exist "D:\githubRunner\_work\_temp" rmdir /s /q "D:\githubRunner\_work\_temp"

      - name: Wait for resource release
        run: timeout /t 5

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          clean: true


      - name: Parasoft Coverage
        uses: parasoft/parasoft-coverage-action@don_cicd985
        with:
            report: '**/coverage.xml'          
